name: actions
on: [push]
jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.16.0'
      - run: npm --version